package com.example.detectionapplication

import android.content.Context
import android.graphics.Bitmap
import android.graphics.RectF
import android.util.Log
import org.json.JSONObject
import org.tensorflow.lite.Interpreter
import java.io.FileInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.MappedByteBuffer
import java.nio.channels.FileChannel

/**
 * On-device YOLOv8 detector for CUSTOM trained models.
 *
 * Optimized for mid-range phones:
 *  - 320×320 input resolution (faster than 640)
 *  - GPU delegate enabled if available
 *  - Float16 quantization reduces memory usage
 *  - Expected: 10-15 FPS on Snapdragon 7xx / 2-3 year old devices
 *
 * MODEL FILES (both must be in assets/):
 *  - model.tflite           ← your converted custom model
 *  - class_names.json       ← generated by convert_to_tflite.py
 */
class OnDeviceDetector(private val context: Context) {

    companion object {
        private const val MODEL_FILE       = "best.tflite"
        private const val CLASS_NAMES_FILE = "class_names_best.json"
        private const val INPUT_SIZE       = 320
        private const val CONF_THRESHOLD   = 0.45f
        private const val IOU_THRESHOLD    = 0.45f
    }

    private var interpreter: Interpreter? = null
    private val inputBuffer: ByteBuffer
    private val outputBuffer: Array<Array<FloatArray>>

    // Loaded from class_names.json
    private var numClasses:  Int = 0
    private var classLabels: Array<String> = emptyArray()

    init {
        // Load class names first so we know how many output channels to allocate
        loadClassNames()

        // Allocate buffers
        inputBuffer = ByteBuffer.allocateDirect(1 * INPUT_SIZE * INPUT_SIZE * 3 * 4)
            .order(ByteOrder.nativeOrder())

        // Output: [1, 4 + numClasses, 2100]
        // 2100 = number of anchor boxes at 320×320
        outputBuffer = Array(1) { Array(4 + numClasses) { FloatArray(2100) } }

        loadModel()
    }

    // ── Load class names from JSON ────────────────────────────────────────────

    private fun loadClassNames() {
        try {
            val json = context.assets.open(CLASS_NAMES_FILE).bufferedReader().use { it.readText() }
            val obj  = JSONObject(json)

            numClasses  = obj.getInt("num_classes")
            val names   = obj.getJSONArray("class_names")
            classLabels = Array(names.length()) { i -> names.getString(i) }

            Log.i("OnDeviceDetector", "Loaded $numClasses classes: ${classLabels.toList()}")
        } catch (e: Exception) {
            Log.e("OnDeviceDetector", "Failed to load class_names.json: ${e.message}")
            throw e
        }
    }

    // ── Load TFLite model ─────────────────────────────────────────────────────

    private fun loadModel() {
        try {
            val modelBuffer = loadModelFile()
            val options     = Interpreter.Options()

            // CPU mode with 4 threads (no GPU to avoid dependency issues)
            options.setNumThreads(4)
            Log.i("OnDeviceDetector", "Using CPU mode (4 threads)")

            interpreter = Interpreter(modelBuffer, options)
            Log.i("OnDeviceDetector", "TFLite model loaded: $MODEL_FILE")

        } catch (e: Exception) {
            Log.e("OnDeviceDetector", "Model load failed: ${e.message}")
            throw e
        }
    }

    private fun loadModelFile(): MappedByteBuffer {
        val fd     = context.assets.openFd(MODEL_FILE)
        val stream = FileInputStream(fd.fileDescriptor)
        val channel = stream.channel
        return channel.map(FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength)
    }

    // ── Inference ─────────────────────────────────────────────────────────────

    data class DetectedObject(
        val classId:    Int,
        val className:  String,
        val confidence: Float,
        val bbox:       RectF
    )

    fun detect(
        bitmap:        Bitmap,
        targetClasses: List<String>
    ): List<DetectedObject> {

        val startMs = System.currentTimeMillis()

        preprocessBitmap(bitmap)
        interpreter?.run(inputBuffer, outputBuffer) ?: return emptyList()

        val detections = postprocess(
            output        = outputBuffer[0],
            originalW     = bitmap.width,
            originalH     = bitmap.height,
            targetClasses = targetClasses
        )

        val elapsedMs = System.currentTimeMillis() - startMs
        Log.d("OnDeviceDetector", "Inference: ${elapsedMs}ms | ${detections.size} objects")

        return detections
    }

    // ── Preprocessing ─────────────────────────────────────────────────────────

    private fun preprocessBitmap(bitmap: Bitmap) {
        val resized = Bitmap.createScaledBitmap(bitmap, INPUT_SIZE, INPUT_SIZE, true)
        inputBuffer.rewind()

        val pixels = IntArray(INPUT_SIZE * INPUT_SIZE)
        resized.getPixels(pixels, 0, INPUT_SIZE, 0, 0, INPUT_SIZE, INPUT_SIZE)

        // Normalize to [0, 1]
        for (pixel in pixels) {
            val r = ((pixel shr 16) and 0xFF) / 255.0f
            val g = ((pixel shr  8) and 0xFF) / 255.0f
            val b = ((pixel       ) and 0xFF) / 255.0f
            inputBuffer.putFloat(r)
            inputBuffer.putFloat(g)
            inputBuffer.putFloat(b)
        }
    }

    // ── Postprocessing ────────────────────────────────────────────────────────

    private fun postprocess(
        output:        Array<FloatArray>,   // [4 + numClasses, 2100]
        originalW:     Int,
        originalH:     Int,
        targetClasses: List<String>
    ): List<DetectedObject> {

        val targetClassIds = if (targetClasses.isEmpty()) {
            null
        } else {
            targetClasses.mapNotNull { name ->
                classLabels.indexOfFirst { it.equals(name, ignoreCase = true) }
                    .takeIf { it >= 0 }
            }.toSet()
        }

        val boxes     = mutableListOf<DetectedObject>()
        val numBoxes  = output[0].size  // 2100

        for (i in 0 until numBoxes) {
            val cx = output[0][i]
            val cy = output[1][i]
            val w  = output[2][i]
            val h  = output[3][i]

            // Find best class
            var maxConf   = 0f
            var bestClass = -1
            for (c in 0 until numClasses) {
                val conf = output[4 + c][i]
                if (conf > maxConf) {
                    maxConf   = conf
                    bestClass = c
                }
            }

            if (maxConf < CONF_THRESHOLD) continue
            if (targetClassIds != null && bestClass !in targetClassIds) continue

            // Convert normalized coords to pixel coords
            val x1_norm = cx - w / 2
            val y1_norm = cy - h / 2
            val x2_norm = cx + w / 2
            val y2_norm = cy + h / 2

            val scaleX = originalW.toFloat()
            val scaleY = originalH.toFloat()

            boxes.add(
                DetectedObject(
                    classId    = bestClass,
                    className  = classLabels[bestClass],
                    confidence = maxConf,
                    bbox       = RectF(
                        x1_norm * scaleX,
                        y1_norm * scaleY,
                        x2_norm * scaleX,
                        y2_norm * scaleY
                    )
                )
            )
        }

        return nonMaxSuppression(boxes)
    }

    // ── NMS ───────────────────────────────────────────────────────────────────

    private fun nonMaxSuppression(boxes: List<DetectedObject>): List<DetectedObject> {
        val sorted = boxes.sortedByDescending { it.confidence }
        val keep   = mutableListOf<DetectedObject>()

        for (box in sorted) {
            var shouldKeep = true
            for (kept in keep) {
                if (iou(box.bbox, kept.bbox) > IOU_THRESHOLD) {
                    shouldKeep = false
                    break
                }
            }
            if (shouldKeep) keep.add(box)
        }
        return keep
    }

    private fun iou(a: RectF, b: RectF): Float {
        val interLeft   = maxOf(a.left, b.left)
        val interTop    = maxOf(a.top, b.top)
        val interRight  = minOf(a.right, b.right)
        val interBottom = minOf(a.bottom, b.bottom)

        val interArea = maxOf(0f, interRight - interLeft) * maxOf(0f, interBottom - interTop)
        val areaA     = a.width() * a.height()
        val areaB     = b.width() * b.height()

        return interArea / (areaA + areaB - interArea + 1e-6f)
    }

    // ── Cleanup ───────────────────────────────────────────────────────────────

    fun close() {
        interpreter?.close()
        interpreter = null
    }
}